version: '3.8'

services:
  postgres_db:
    image: postgres:17.0
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME} 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prestamo_network

  micro_prestamo_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: micro_prestamo_service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - postgres_db
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_DATABASE}
    networks:
      - prestamo_network

networks:
  prestamo_network: {}

volumes:
  postgres_data:
